const routes={
 '/home':'home','/':'home','/about':'about','/scripts':'scripts','/books':'books','/work-in-progress':'wip','/corporate-cv':'cv','/branded':'branded','/blog':'blog','/contact':'contact','/games':'games'
};
const nav=[['/about','About'],['/scripts','Scripts'],['/books','Books'],['/work-in-progress','WIP'],['/corporate-cv','CV'],['/branded','Branded'],['/games','Games'],['/blog','Blog'],['/contact','Contact']];
const $=s=>document.querySelector(s);let data;
const local=true;
const link=path=>`#${path}`;
const currentPath=()=>location.hash.slice(1)||'/home';
function header(){const path=currentPath();return `<header class="nav"><a class="logo" href="${link('/home')}">Cyril Prytula</a><button class="menu" aria-label="Open menu">Menu +</button><nav class="nav-links">${nav.map(([u,n])=>`<a class="${path===u?'active':''}" href="${link(u)}">${n}</a>`).join('')}</nav></header>`}
function footer(){return `<footer><span>© Cyril Prytula, 2026</span><a href="${link('/contact')}">Let’s make something →</a></footer>`}
function home(){return `<section class="hero"><p class="eyebrow">Writer · Screenwriter · Producer</p><h1>Telling stories<br>& making them real</h1><p class="lead">Since 2008 — film, television, books, branded stories and interactive worlds.</p></section><main class="wrap"><section class="statement"><h2>Stories that move from a first thought to something people can watch, read and play.</h2><p>Explore scripts, books, work in progress and selected branded projects.</p></section><section class="grid">${data.homeCards.map((c,i)=>`<a class="card" href="${link(c.url)}"><span class="number">0${i+1}</span><div><p class="tag">${c.tag}</p><h3>${c.title}</h3></div><span class="arrow">Discover ↗</span></a>`).join('')}</section></main>`}
function collection(key){const s=data.sections[key];return `<section class="section-hero ${key}"><p class="eyebrow">Archive / ${s.kicker}</p><h1>${s.title}</h1><p>${s.intro}</p></section><main class="section-content"><p>${s.body}</p><section class="collection">${s.items.map((x,i)=>`<article class="project"><span class="tag">${String(i+1).padStart(2,'0')} / ${x.meta}</span><div><h2>${x.title}</h2><p>${x.text}</p></div>${x.link?`<a href="${x.link}">Open project ↗</a>`:''}</article>`).join('')}</section></main>`}
function about(){let s=data.sections.about;return `<section class="section-hero"><p class="eyebrow">About / Lisbon, Portugal</p><h1>Let’s make great content without boundaries.</h1></section><main class="section-content"><p>${s.body}</p><p>${s.extra}</p><section class="collection">${s.items.map(x=>`<article class="project"><span class="tag">Personal notes</span><div><h2>${x.title}</h2><p>${x.text}</p></div></article>`).join('')}</section></main>`}
function cv(){let s=data.sections.cv;return `<section class="section-hero"><p class="eyebrow">Selected experience</p><h1>Corporate CV</h1><p>${s.intro}</p></section><main class="section-content">${s.items.map(x=>`<section class="cv"><time>${x.period}</time><div><h2>${x.title}</h2><p>${x.text}</p></div></section>`).join('')}</main>`}
function contact(){return `<main class="contact"><div><p class="eyebrow">New work, old stories, good ideas</p><h1>Say<br>hello.</h1><p>For collaborations, scripts and conversation:</p><a class="email" href="mailto:${data.contactEmail}">${data.contactEmail}</a></div></main>`}
function render(){let page=routes[currentPath()]||'home';let content=page==='home'?home():page==='about'?about():page==='cv'?cv():page==='contact'?contact():collection(page);$('#app').innerHTML=(page==='contact'?'':header())+content+footer();$('.menu')?.addEventListener('click',()=>$('.nav').classList.toggle('open'));}
const previewData={contactEmail:'hello@prytula.eu',homeCards:[{title:'Scripts',tag:'Film & television',url:'/scripts'},{title:'Books',tag:'Novels & stories',url:'/books'},{title:'Work in progress',tag:'What’s next',url:'/work-in-progress'},{title:'Branded',tag:'Projects for brands',url:'/branded'},{title:'Games',tag:'Playable stories',url:'/games'},{title:'Blog',tag:'Notes & thoughts',url:'/blog'}],sections:{about:{body:'Cyril Prytula is a writer, screenwriter and producer with more than 15 years of experience across production companies, streaming platforms and TV networks.',extra:'Based in Lisbon, Portugal, Cyril works on new screenplays, a second SF novel, narrative design for a game studio and a collection of short stories.',items:[{title:'Stories first',text:'Building content that has a point of view, a human voice and an audience in mind.'}]},scripts:{title:'Scripts',kicker:'Film & television',intro:'Screen stories for features, series and formats.',body:'A selected archive of screenwriting and production work.',items:[{title:'Featured script',meta:'Screenplay / year',text:'Add title, logline and viewing link here.'}]},books:{title:'Books',kicker:'Novels & stories',intro:'Long-form worlds and stories that stay with you.',body:'A growing shelf of published work, drafts and new ideas.',items:[{title:'TAS: The Moscow Collective',meta:'Novel',text:'Add a brief description, cover image and purchase link.'}]},wip:{title:'Work in progress',kicker:'What’s next',intro:'Projects still becoming themselves.',body:'Films, books, interactive work and other stories currently in development.',items:[{title:'New screenplay',meta:'In development',text:'Add a short spoiler-free note.'}]},branded:{title:'Branded',kicker:'Stories for brands',intro:'Advertisement scripts, branded content and visual storytelling.',body:'Developed advertisement scripts for more than ten brands and worked with several agencies.',items:[{title:'Brand project one',meta:'Branded content',text:'Add a project name, your role and a video link.'}]},games:{title:'Games',kicker:'Playground / 01—∞',intro:'Small interactive worlds, branded games and experiments.',body:'Pick a story and step inside.',items:[{title:'Game title goes here',meta:'Branded game / 2026',text:'Add a short one-line description and game link.'}]},blog:{title:'Blog',kicker:'Notes & thoughts',intro:'A few words between projects.',body:'Use this space for writing, creative process, news and useful links.',items:[{title:'First note',meta:'Date',text:'Add your first post title and excerpt.'}]},cv:{title:'Corporate CV',intro:'A selected overview of experience across writing, production and story development.',items:[{period:'2008 — now',title:'Writer, screenwriter & producer',text:'Feature films, mini-series and long-running TV projects.'}]}}};
fetch('/data/site.json').then(r=>r.json()).then(x=>{data=x;render()}).catch(()=>{data=previewData;render()});
window.addEventListener('hashchange',()=>{if(local)render()});
